import startImg from "../assets/images/startImg.png";
import Login from "@/assets/images/login.png";
import Arrow from "@/assets/images/arrow.png";
import LoginVerify from "@/assets/images/loginVerify.png";
import verifiedEmail from "@/assets/images/verifiedEmail.png";
import phoneVerify from "@/assets/images/phoneVerify.png";
import banner from "@/assets/images/tab/banner.png";
import user from "@/assets/images/tab/user.png";
import notice from "@/assets/images/tab/notice.png";
import logoSmall from "@/assets/images/tab/logoSmall.png";
import completeProfile from "@/assets/images/tab/completeProfile.png";
import search from "@/assets/images/tab/search.png";
import users from "@/assets/images/users.png";
import quiz from "@/assets/images/tab/quiz.png";
import planning1 from "@/assets/images/tab/planning1.png";
import planning2 from "@/assets/images/tab/planning2.png";
import planning3 from "@/assets/images/tab/planning3.png";
import home from "@/assets/images/tab/home.png";
import message from "@/assets/images/tab/message.png";
import arrowBlack from "@/assets/images/arrowBlack.png";
import skills1 from "@/assets/images/skills1.png";
import add from "@/assets/images/add.png";
import close from "@/assets/images/close.png";
import role from "@/assets/images/role.png";
import addExperience from "@/assets/images/tab/addExperience.png";
import addArrow from "@/assets/images/tab/addArrow.png";
import angle from "@/assets/images/tab/angle.png";
import profile from "@/assets/images/setting/profile.png";
import subscriptionSetting from "@/assets/images/setting/subscription.png";
import certificationsSetting from "@/assets/images/setting/certificate.png";
import password from "@/assets/images/setting/password.png";
import support from "@/assets/images/setting/support.png";
import bills from "@/assets/images/setting/bills.png";
import arrowIcon from "@/assets/images/setting/arrow.png";
import logout from "@/assets/images/setting/logout.png";
import settingUser from "@/assets/images/setting/user.png";
import edit from "@/assets/images/tab/edit.png";
import deleteBtn from "@/assets/images/tab/delete.png";
import certificate from "@/assets/images/certificate.png";
import language from "@/assets/images/language.png";
import Bio from "@/assets/images/bio.png";



export default {Bio,language, certificate,deleteBtn,edit,settingUser,logout,arrowIcon,bills,support,password,certificationsSetting,subscriptionSetting,profile,angle,addArrow,addExperience,role,close,add,skills1,arrowBlack,message,home,planning3,planning2,planning1,quiz,users,startImg ,Login,Arrow,LoginVerify,verifiedEmail,phoneVerify,banner,user,notice,logoSmall,completeProfile,search};